# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt:
    edw_trans:
      +database: >-
        {%- if target.name == 'dev' -%} dev_tran_edw
        {%- elif target.name == 'qa' -%} qa_tran_edw
        {%- else -%} prod_tran_edw {%- endif -%}
      employee:
        +schema: employee
        +materialized: table
      customer:
        +schema: customer
        +materialized: table

    edw_pres:
      +database: >-
        {%- if target.name == 'dev' -%} dev_analytics_edw
        {%- elif target.name == 'qa' -%} qa_analytics_edw
        {%- else -%} prod_analytics_edw {%- endif -%}
      +schema: pres
      +materialized: view

seeds:
  dbt:
    +database: >-
      {%- if target.name == 'dev' -%} dev_tran_edw
      {%- elif target.name == 'qa' -%} qa_tran_edw
      {%- else -%} prod_tran_edw {%- endif -%}
    +schema: master