user:
  outputs:
    dev:
      account: BZQHTOO-NNC60520
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: dev_analytics_edw
      password: H@rsha9966699546
      retry_on_database_errors: true
      role: ACCOUNTADMIN
      schema: dev_analytics_edw
      threads: 6
      type: snowflake
      user: tatimatla
      warehouse: COMPUTE_WH
  target: dev
